#!/usr/bin/env bash
set -euo pipefail

CLUSTER_NAME="${CLUSTER_NAME:-kctx-lab}"
NAMESPACE="${NAMESPACE:-argocd}"
TIMEOUT="${TIMEOUT:-300s}"
ARGOCD_NODE_PORT="${ARGOCD_NODE_PORT:-30443}"
ARGOCD_HOST_PORT="${ARGOCD_HOST_PORT:-8443}"
MANIFEST_URL="${MANIFEST_URL:-https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml}"

# Print a visible step message to stderr.
log() {
  printf '\n==> %s\n' "$*" >&2
}

# Print an error message and stop the script.
fail() {
  printf 'error: %s\n' "$*" >&2
  exit 1
}

# Ensure that a required command is available before continuing.
require() {
  command -v "$1" >/dev/null 2>&1 || fail "missing required command: $1"
}

require kind
require kubectl

# The kind cluster must already exist with the ArgoCD NodePort mapped by kind-up.sh.
kind get clusters | grep -Fxq "${CLUSTER_NAME}" || fail "kind cluster '${CLUSTER_NAME}' not found; run scripts/kind-up.sh first"

log "using kind context"
kubectl config use-context "kind-${CLUSTER_NAME}" >/dev/null

log "creating namespace '${NAMESPACE}'"
kubectl create namespace "${NAMESPACE}" --dry-run=client --output yaml | kubectl apply -f -

log "installing ArgoCD"
# Use server-side apply because ArgoCD CRDs can exceed the client-side apply annotation limit.
kubectl apply \
  --server-side \
  --force-conflicts \
  --field-manager install-argocd \
  --namespace "${NAMESPACE}" \
  -f "${MANIFEST_URL}"

log "exposing ArgoCD server with NodePort ${ARGOCD_NODE_PORT}"
kubectl patch service argocd-server \
  --namespace "${NAMESPACE}" \
  --type merge \
  --patch "{\"spec\":{\"type\":\"NodePort\",\"ports\":[{\"name\":\"http\",\"port\":80,\"protocol\":\"TCP\",\"targetPort\":8080},{\"name\":\"https\",\"port\":443,\"protocol\":\"TCP\",\"targetPort\":8080,\"nodePort\":${ARGOCD_NODE_PORT}}]}}"

log "waiting for ArgoCD pods"
kubectl wait --namespace "${NAMESPACE}" --for=condition=Ready pod --all --timeout="${TIMEOUT}"

# The initial admin password is generated by ArgoCD and stored in a Kubernetes Secret.
INITIAL_PASSWORD="$(kubectl get secret argocd-initial-admin-secret --namespace "${NAMESPACE}" --output jsonpath='{.data.password}' | base64 --decode)"

cat <<EOF

ArgoCD is ready.

Namespace:  ${NAMESPACE}
URL:        https://localhost:${ARGOCD_HOST_PORT}
Username:   admin
Password:   ${INITIAL_PASSWORD}

The ArgoCD server uses a self-signed certificate by default, so your browser may show a certificate warning.

Try:
  kubectl get pods --namespace ${NAMESPACE}
  kubectl get service argocd-server --namespace ${NAMESPACE}

EOF
